-- this is a comment

SELECT `TABLE_SCHEMA`,`TABLE_NAME`,`COLUMN_NAME`,`ORDINAL_POSITION`
FROM `information_schema`.`COLUMNS`
WHERE `TABLE_SCHEMA` = "information_schema" AND `TABLE_NAME` = "COLUMNS"
ORDER BY `ORDINAL_POSITION` ASC
LIMIT 25;
