monthly_check:
  source: /home/ahorgnies/sources/sql
  output: /home/ahorgnies/reports
mysql:
  host: 127.0.0.1
  user: root
logging:
  level: DEBUG
  format: '%(asctime)s %(name)s:%(lineno)d %(levelname)s %(message)s'
